### ISSUE TITLE
Missing SVProgressHUD.bundle when installing SVProgressHUD 1.1.3 via Cocoapods

### ISSUE THREAD

**Issue by yujean** [SVProgressHUD/SVProgressHUD#449] opened 2015-07-07 19:25 UTC
I recently attempted to do `pod install`, after updating my `SVProgressHUD` from `1.1.2` to `1.1.3`, and `SVProgressHUD.bundle` seemed to be missing.

In `SVProgressHUD.m:266`:

``NSURL *url = [bundle URLForResource:@"SVProgressHUD" withExtension:@"bundle"];``

`url` will return nil, triggering an exception on the next line:

``NSBundle *imageBundle = [NSBundle bundleWithURL:url];``

The exception is as follows:

``*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'``

Manually dragging the SVProgressHUD.bundle from the Pods/SVProgressHUD/SVProgressHUD/ folder on the filesystem, into my Xcode project (which is in the embedded Xcode workspace) will get rid of this exception.

**Comment by jamonholmgren** [comment] 2015-07-11 19:50
Running into this same issue.

**Comment by joshuafeldman** [comment] 2015-07-19 03:10
I see the same issue. Looks like the bundle is not correctly getting copied

**Comment by honkmaster** [comment] 2015-07-19 09:13
My main issue might be that I am not using Cocoapods on my own ... Most of the time we had an issue like this it was due to that the bundle was (like you already identified) not copied during one of the build phases ("Copy bundled resources"). Manually adding the bundle to this phase resolved the issue. Generally: PR are very welcome.

**Comment by alexeyhippie** [comment] 2015-08-14 15:12
Hey there, 

Same issue, but app getting crash in ```_dispatch_once``` function, after ```+sharedView``` method. Diving in shows that there is nil in bundle image url

**Comment by algal** [comment] 2015-08-21 00:35
Same issue here. This seems to be a pretty bug introduced in 1.1.3.. Not sure if it only shows up with certain cocoapod configurations.

**Comment by honkmaster** [comment] 2015-09-01 08:48
Hmm. I am not using cocoapods daily and thus I am not sure how to fix this bug.

**Comment by Dids** [comment] 2015-09-10 07:03
My app just got rejected because of this (most likely anyway, from what I can tell from the crash logs).
Thing is, I'm unable to replicate this. The app runs fine on my devices and simulators.

**Comment by Dids** [comment] 2015-09-20 10:53
Any news on this?

**Comment by hhanesand** [comment] 2015-10-27 01:06
I've just manually added the `SVProgressHUD.bundle` to my target's copy build phase. There might be something with the configuration of the `podspec` that is not jibing with our setups, but I haven't looked into it.

**Comment by honkmaster** [comment] 2015-11-06 14:37
I updated the pod, please be aware that 2.0 is in beta status right now.

**Comment by batuorhanalp** [comment] 2015-11-12 12:59
Turned back to 1.1.2 and problem solved.

**Comment by honkmaster** [comment] 2015-11-12 13:00
Why not try the 2.0 beta?

**Comment by batuorhanalp** [comment] 2015-11-12 13:27
I got the same error while using 2.0 beta. You can see the stack detail below.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
>	0   CoreFoundation                      0x00d97946 __exceptionPreprocess + 182
>	1   libobjc.A.dylib                     0x03523a97 objc_exception_throw + 44
>	2   CoreFoundation                      0x00d9786d +[NSException raise:format:] + 141
>	3   Foundation                          0x03184c4a -[NSBundle initWithURL:] + 102
>	4   Foundation                          0x03184d21 +[NSBundle bundleWithURL:] + 68
>	5   FarmerForm                          0x00221ad6 -[SVProgressHUD initWithFrame:] + 902
>	6   FarmerForm                          0x0021faa7 __27+[SVProgressHUD sharedView]_block_invoke + 311
>	7   libdispatch.dylib                   0x038b3e2f _dispatch_client_callout + 14
>	8   libdispatch.dylib                   0x0389e76c dispatch_once_f + 363
>	9   libdispatch.dylib                   0x0389e5fc dispatch_once + 31
>	10  FarmerForm                          0x0021f932 +[SVProgressHUD sharedView] + 162
>	11  FarmerForm                          0x00220627 +[SVProgressHUD showWithMaskType:] + 55

libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by honkmaster** [comment] 2015-11-12 13:48
Seems tghat the `SVProgressHUD.bundle` is still missing and not copied. However I have no odea how to solve this issue with Cocoapods.

**Comment by honkmaster** [comment] 2015-11-12 18:28
I do not use this system, and thus can not help good. I think we have to find a solution for 2.0, but I do not have the time to investigate. Where are the Cocoapods gurus?! Le me phrase it very hard, if this issue persists we have to remove Cocoapod support because I can not maintain it.

**Comment by tar500** [comment] 2015-11-16 22:56
@Dids 

>My app just got rejected because of this (most likely anyway, from what I can tell from the crash logs).
>Thing is, I'm unable to replicate this. The app runs fine on my devices and simulators.

I've just run into the same issue, but with a different .bundle.
We use jenkins for building an .ipa, and we used an option "Generate Archive" in Xcode plugin.
It appears that using that option (which runs /usr/bin/xcrun) creates an archive without Cocoapods resources (cocoapods copy resources run script didn't work for some reason, I'm still investigating).

So we tested an .ipa, and everything worked great.
Then we have uploaded a build to the App Store from generated .xcarchive. For some reason it passed Apple Review despite the crash. And then we have discovered a crash because of similar bug.

I found that .xcarchive/Products/MyApp.app/ does not contain .bundle that should be there.
But .ipa does.

We are able to reproduce a crash on our devices when we create a build for devices from that archive.

Hope this will help someone to figure out what's going on.

**Comment by x2on** [comment] 2015-11-20 11:30
Here looks all fine. 
Using 1.1.3 works good here with CocoaPods.

Probably it helps to update CocoaPods to latest version

**Comment by x2on** [comment] 2015-11-20 11:30
Also the current `master` works fine with CocoaPods here.

**Comment by honkmaster** [comment] 2015-11-20 11:35
That's good to hear. However, so many people complained. Therefore I think this is a valid issue, and will remain as long as I get enough positive feedback. And still I have no real idea what to do ...

**Comment by hilen** [comment] 2015-11-25 09:09
@x2on What's your pod version ? Mine is 0.39.0 , not work for me in Swift project.

**Comment by ashvar** [comment] 2015-12-02 00:26
1.1.3 is not working for me.

**Comment by honkmaster** [comment] 2015-12-07 20:49
@ashvar could you please try the latest master?

**Comment by mabuhegde** [comment] 2015-12-08 10:53
same here. I am using SVProgressHUD 1.1.3 cocoapods 0.38.2 version in a swift project. SVProgressHUD only showing when i killed the app and relaunch. i tried 1.1.2 no luck. I am about to release my app.

**Comment by racarate** [comment] 2016-01-10 22:18
1.1.3 is causing a crash for me when I try to build https://github.com/aclissold/The-Oakland-Post.

@hhanesand's suggestion of adding an item to the "Copy Bundle Resources" build phase fixed the problem.

**Comment by hhanesand** [comment] 2016-01-12 18:28
The use of `resources` is "deprecated" in cocoapods anyways, so I can submit a pull changing the `podspec` to use  `resource_bundles` later today. That may or may not fix the issue.

Can people who are experiencing the problem share their `podfile` and what version they are linking against in the future? Curious to see if the use of `!use_frameworks` affects this at all.

**Comment by honkmaster** [comment] 2016-01-18 22:57
Another try. Should be fixed due to https://github.com/SVProgressHUD/SVProgressHUD/commit/de93d1cdcbf76db6d6526db2b629760413cddea8 and #542.

**Closed** 2016-01-18 22:57 UTC
Labels: Bug, Under investigation

**Comment by hhanesand** [comment] 2016-01-19 13:51
:+1:

**Comment by freemiumdev** [comment] 2016-03-29 09:44
I've the same problem with version 2.0, and I solved it by deleting the contents of the folder "derived data" and rebuild all.

**Comment by neywen** [comment] 2016-04-14 10:15
I'm having the same issue right now after updated to 'SVProgressHUD', '~> 2.0.3'
Deleting the Derived data did not help.

Here is the contents of my Podfile : 

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
pod 'AFNetworking',  '~> 3.1.0'
pod 'Reachability',  '~> 3.2'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SSKeychain', '~> 1.4.0'
pod 'Fabric', '~> 1.6.7'
pod 'Crashlytics', '~> 3.7.0'
pod 'Mapbox-iOS-SDK', '~> 3.2.0'
pod 'LoremIpsum', '~> 1.0.0'
pod 'RFQuiltLayoutCH', '~> 1.1.2'
pod 'FBSDKCoreKit', '~> 4.11.0'
pod 'FBSDKShareKit', '~> 4.11.0'
pod 'iOS-Slide-Menu', '~> 1.5'
pod 'MMMarkdown', '~> 0.5.2'
pod 'Analytics', '~> 3.0.7'
pod 'Amplitude-iOS', '~> 3.6.0'
pod 'TWMessageBarManager', '~> 1.8.1'
pod 'UAObfuscatedString', '~> 0.3.2'

target '[MY TARGET]' do
end

```

I removed the pod, and used the last github master for now. It fixed the problem.

**Comment by edwardmp** [comment] 2016-05-11 19:31
I encountered this issue today too but did not encounter it before. It ocurred after I changed my podfile to include `use_frameworks!`

**Comment by andrewreeman** [comment] 2016-06-10 11:12
I 'solved' this by not using pods for SVProgressHUD and simply adding it manually to the project instead.

**Comment by fyt10060** [comment] 2016-07-22 09:03
@yujean "Manually dragging the SVProgressHUD.bundle from the Pods/SVProgressHUD/SVProgressHUD/ folder on the filesystem, into my Xcode project (which is in the embedded Xcode workspace) will get rid of this exception."  many other people suggest this solution didn't work for me....I solve this bug by adding SVProgressHUD  manually to my project.....

My situation is very interesting. I use SVProgressHUD in both the main target and the extension target. At first, only the extension target had this problem, but the main target worked well, after my struggle, this problem affect both two targets....

**Comment by yujean** [comment] 2016-07-22 09:11
@fyt10060 That's odd.  Perhaps you should double-check to make sure the SVProgressHUD.bundle's "Target Membership" check boxes are checked for the Targets you intend to use them with.  This can be performed by selecting "SVProgressHUD.bundle" from the left Navigator pane in Xcode (cmd-zero to open/close), then checking the boxes in the right Utilities pane (cmd-option-zero to open/close).

**Comment by RaimundWege** [comment] 2016-09-09 12:34
fyi: I ran into the same missing bundle issue with cocoapods. But my project isn't a standard cocoapods project - because of a necessary maven build process I can't use Xcode workspaces... So I've added the Pods project as a sub-project to my app-project and got this error. I could fix the issue by adding the SVProgressHUD.bundle to 'Copy Bundle Resources' of my app target.

**Comment by SevenHL** [comment] 2017-04-12 07:21
I use the 2.0.3 version have appeared in the bundle error, using the pod update to update to the latest version solved the problem

**Comment by qzytcl** [comment] 2018-07-02 06:55
Xcode 10.0 beta 2
pod update 
version 2.2.5
405 row's url nil.
