### ISSUE TITLE
in swift, an issure of dissmiss and show...

### ISSUE THREAD

**Issue by tl454251115** [SVProgressHUD/SVProgressHUD#641] opened 2016-07-06 07:29 UTC
SVProgressHUD.showWithStatus(nil)
dispatch_async......... {
SVProgressHUD.dismiss()
SVProgressHUD.showErrorWithStatus("error")
}

why did not ' SVProgressHUD.showErrorWithStatus("error") ' show?

**Comment by honkmaster** [comment] 2016-08-01 21:20
Should be fixed with the latest commit, please check the current master and provide feedback.

**Comment by honkmaster** [comment] 2016-08-23 09:26
No feedback at all? This is sad.

Questions and issues like this, are the reason people burn out on open source. Don't let others do your work, give good questions, follow issue guidelines, provide a demo project or tell what you have already done to solve the problem. Also give feedback if required! This is a matter of respect fot the programmers that make a lot of efforts on writing open source components.

**Comment by adriantofan** [comment] 2016-10-05 15:49
I've had the same issue and I can confirm that updating fixed the issue.
Thank you all

**Comment by BrikerMan** [comment] 2016-11-15 04:58
I've had the same issue and I can confirm that updating fixed the issue.
Thank you all~

**Closed** 2016-11-15 11:23 UTC
Labels: Bug, Waiting for feedback
