### ISSUE TITLE
setDefaultMaskType not work

### ISSUE THREAD

**Issue by FrostBest** [SVProgressHUD/SVProgressHUD#735] opened 2017-03-11 04:19 UTC
SVProgressHUD.setDefaultMaskType(.gradient)
not work

**Comment by NOlivNeto** [comment] 2017-03-14 16:59
This issue is a duplicate of #719 

`setDefaultMaskType` is apparently only not working with `.gradient` in Swift 3 since version 2.1.2, at least. `.black` and `.white` seems to be ok.

**Comment by honkmaster** [comment] 2017-04-30 14:59
Can someone provide a swift demo project?

**Comment by honkmaster** [comment] 2017-05-07 13:04
Should be working again.

**Closed by honkmaster** 2017-05-07 13:04 UTC
