### ISSUE TITLE
Can fix iOS 10 'UINotificationFeedbackGenerator' is partial: introduced in iOS 10.0 issues???

### ISSUE THREAD

**Issue by sweetmans** [SVProgressHUD/SVProgressHUD#856] opened 2018-01-10 06:45 UTC
You framework in swift4 with iOS 9.0 support show this issues.
`#if TARGET_OS_IOS && __IPHONE_OS_VERSION_MAX_ALLOWED >= 100000
- (UINotificationFeedbackGenerator *)hapticGenerator {
	// Only return if haptics are enabled
	if(!self.hapticsEnabled) {
		return nil;
	}
	
	if(!_hapticGenerator) {
		_hapticGenerator = [[UINotificationFeedbackGenerator alloc] init];
	}
	return _hapticGenerator;
}
#endif
`
'UINotificationFeedbackGenerator' is partial: introduced in iOS 10.0
'UINotificationFeedbackGenerator' is only available on iOS 10.0 or newer

**Comment by yarodevuci** [comment] 2018-01-13 00:04
@sweetmans Agreed
Will it be taken care of?

**Comment by ricsantos** [comment] 2018-01-14 00:36
This is a duplicate of issue #855 and also pr #821, which silences the warnings but is not compatible with older versions of Xcode [as mentioned here](https://github.com/SVProgressHUD/SVProgressHUD/pull/821#issuecomment-335449955).

**Comment by honkmaster** [comment] 2018-02-12 18:46
Fixed.

**Closed by honkmaster** 2018-02-12 18:46 UTC
