### ISSUE TITLE
How to assign custom values.

### ISSUE THREAD

**Issue by davidseek** [SVProgressHUD/SVProgressHUD#698] opened 2016-12-06 03:33 UTC
Hey. I have tried to figure it out myself, also tried to find a similar open/closed Issue.

In Swift 3, I'm currently opening the HUD as following.

`SVProgressHUD.showProgress(myProgress)`, I would like to change the background color.

If I create an instance of the hud like `let hud = SVProgressHUD()`, I'm able to find the parameters: `hud.hudBackgroundColor = UIColor.blue`, but how do I `.showProgress` on `hud` then?

Or how do I tell `SVProgressHUD.showProgress....`, that I want my instance of `hud` to be "the" hud?

I know you don't support Swift, but I hope I made myself as understandable as possible.

PS Awesome project.

**Comment by honkmaster** [comment] 2016-12-06 07:48
There are custom setters, e.g. `setBackgroundColor:`. Use these instead of accessing the properties directly. They can also be used in Swift without any problem.

**Comment by davidseek** [comment] 2016-12-06 07:57
Thank you for your answer, but I have to admit, that I have no idea how to implement that...

**Comment by honkmaster** [comment] 2016-12-06 08:02
Normally I can not teach you how to program, but ... 

At first `SVProgressHUD` is a singleton. You should not assign it to a variable with let / var. Just use `SVProgressHUD. setBackgroundColor(UIColor.blue())`.

**Comment by davidseek** [comment] 2016-12-06 08:04
Yeah, I'm not asking you to teach me how to program... Thanks for that.
But this is not working. There is not `setXY" on SVProgressHUD...

THAT is why I'm asking.

<img width="506" alt="screen shot 2016-12-06 at 9 03 07 am" src="https://cloud.githubusercontent.com/assets/17073950/20917641/ed0e5424-bb92-11e6-8060-7ac4af302fa5.png">

**Comment by honkmaster** [comment] 2016-12-06 08:20
<img width="809" alt="screen shot 2016-12-06 at 09 19 56" src="https://cloud.githubusercontent.com/assets/1380397/20918015/32f251fa-bb95-11e6-8660-9d2a5b79c89f.png">

**Comment by honkmaster** [comment] 2016-12-06 08:22
This is one of my Swift projects, I just added `SVProgressHUD` for testing purposes and it works as expected. Do you have a minimal sample project with this bug? As I can not reproduce your issue, this is the only way to help.

**Comment by davidseek** [comment] 2016-12-06 08:24
Since it was obviously working with your project, I've tried the only thing that came up in my mind... 

`Installing SVProgressHUD 2.1.1 (was 1.0)`

Now I have the setters...

**Comment by honkmaster** [comment] 2016-12-06 10:12
Ok, great! Just because I am interested: Could you tell me how you integrated SVProgressHUD in Version 1.0? Did you point Cocoapods directly to this version, like `pod 'SVProgressHUD', '~> 1.0'`? 

BTW: I do not wanted to be "rude", but I get "simple" questions like this almost every day. Sorry for that.

**Comment by davidseek** [comment] 2016-12-06 14:06
Your Framework was integrated into some 2 year old sample project, by pointing to 1.0
While re-coding it to Swift 3, I have noticed your Framework and since I have just implemented something with progress, into another project, I have copy/pasted the pod.

And yeah. It's fine. And I get, that it was a simple question, but as you saw, it was not my lack of knowledge...

By the way, you could save time, if you would offer a documentation... I have checked that before asking.

<img width="586" alt="screen shot 2016-12-06 at 3 05 14 pm" src="https://cloud.githubusercontent.com/assets/17073950/20928294/77cfd68c-bbc5-11e6-80f1-a94b2b4a7c85.png">

Whatever, thanks for your project. Saved time and it came along literally the moment I've needed it.

**Comment by honkmaster** [comment] 2016-12-06 14:07
The whole documentation is inside the Readme.md

**Closed** 2016-12-06 14:06 UTC

**Comment by honkmaster** [comment] 2016-12-06 14:08
BTW: Thanks for your hint about the empty wiki, removed it.
