### ISSUE TITLE
HUD not showing on root view controller in viewDidLoad and viewWillAppear methods

### ISSUE THREAD

**Issue by allaire** [SVProgressHUD/SVProgressHUD#536] opened 2016-01-11 21:39 UTC
I found a bug where SVProgressHUD does not display in `viewDidLoad` and `viewWillAppear` on the initial/root view controller. it works correctly in any other subsequent VC, or if the initial view controller is embed in a navigation controller. I attached bellow what I found and different solutions:

[TTest.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/86426/TTest.zip)

@honkmaster this is related to https://github.com/SVProgressHUD/SVProgressHUD/issues/315

Thanks!

**Comment by honkmaster** [comment] 2016-01-12 08:54
IS this also an issue with the current 2.0-beta? If so, this should be fixed before the release (scheduled to mid january).

**Comment by allaire** [comment] 2016-01-12 14:29
@honkmaster this happen with master currently

**Comment by allaire** [comment] 2016-01-12 14:32
@honkmaster just tried with 2.0 beta tag and it's also broken.

**Comment by honkmaster** [comment] 2016-01-12 14:44
Ok. Will tackle it this evening. BTW: Thanks for the demo project, i`m sure this will help.

**Comment by allaire** [comment] 2016-01-12 14:49
Thanks. you can ping me if you need any help.

Cheers

**Comment by honkmaster** [comment] 2016-01-17 12:42
So, i investigated. This should be related to https://github.com/SVProgressHUD/SVProgressHUD/commit/b4a62cde8c7122a6a0fdee62a3bae690f49ea914. There is a problem with the keyWindow, the bounds are zero in viewDidLoad and thus the Hud has no "reference" for drawing ... To be continued.

**Comment by allaire** [comment] 2016-01-17 14:28
@honkmaster Got it. Adding a bit of delay fix the issue, so that makes sense. Keep us posted

**Comment by honkmaster** [comment] 2016-01-17 19:49
Check the latest beta please. It works for me here, GCD was the key here, thus scheduling the show into the main run loop.

**Comment by honkmaster** [comment] 2016-01-18 18:34
Have to reopen due to #544.

**Comment by allaire** [comment] 2016-01-18 18:38
@honkmaster is `[[NSOperationQueue mainQueue] addOperationWithBlock:^{}]` the same as `dispatch_async(dispatch_get_main_queue(), ^{` ?

**Comment by honkmaster** [comment] 2016-01-18 18:40
`NSOperationQueue`is more high level, like a wrapper around `dispatch_async`. For more details: http://stackoverflow.com/a/13249307

**Comment by honkmaster** [comment] 2016-01-18 19:17
I will rework the show method now on.

**Comment by honkmaster** [comment] 2016-01-18 23:09
Please check 2.0beta-3

**Comment by allaire** [comment] 2016-01-18 23:35
@honkmaster Will test soon. Can you describe a bit the solution you found if adding back the operation to the main queue was broking something else?

Thanks for all the good work!

**Comment by honkmaster** [comment] 2016-01-19 08:56
The main "problem" was that there was a strange call hierachy which was called to show an image (which included that showProgress was called even when we wanted to show an image). This broke the solution with the main run loop. I now separated and refactored the show methods for progress and image (they are now independent) and thus it should work. Hard to explain via text. Check the source code  of the recent commits and look at the `showProgress` method for example.

**Comment by allaire** [comment] 2016-01-19 22:01
@honkmaster Using master, for some reason, after dismissing SVProgressHUD, I can't tap on anything, like if an invisible UIView was over the screen, preventing me from doing anything.

**Comment by honkmaster** [comment] 2016-01-19 22:05
cannot reproduce in the demo application as well as one of my own apps.

**Comment by allaire** [comment] 2016-01-19 22:07
@honkmaster happens when I show a HUD just before pushing a new VC in my navigation controller. happening on Beta3, now trying Beta2 to pin point which version is causing the issue :)

**Comment by honkmaster** [comment] 2016-01-19 22:09
open source life ist not easy :(. sorry.

**Comment by allaire** [comment] 2016-01-19 22:11
@honkmaster Hehe, no worries. So it works in Beta2. I'll spin a new demo trying to isolate the issue I have

**Comment by allaire** [comment] 2016-01-19 22:18
Isolated the issue here: [TTest2.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/96641/TTest2.zip)

**Comment by honkmaster** [comment] 2016-01-19 22:28
Found. Will push fix in five minutes.

**Comment by allaire** [comment] 2016-01-19 22:30
Heh, at least we make a great time at finding issues :smile: 

Good job!

**Comment by honkmaster** [comment] 2016-01-19 22:41
The first bug (not touchable) should be gone. The second one with dismiss is similar to the one with show. Here I have to apply the same solution (move to main run loop), however it's around midnight here and I will continue tomorrow.

**Comment by allaire** [comment] 2016-01-20 14:24
@honkmaster giving beta4 a go. Thanks for the update!

**Comment by allaire** [comment] 2016-01-20 14:30
@honkmaster New issue with beta4, the background show/hide correctly, but no HUD is showing

**Comment by honkmaster** [comment] 2016-01-20 18:03
Related to latest comment in #528.

**Comment by allaire** [comment] 2016-01-20 18:05
![1453313147-9e87db4b709150eb8c8667b47f6096e2](https://cloud.githubusercontent.com/assets/304461/12458172/8b9a2fb0-bf76-11e5-8c84-3f67cc11bf38.jpg)

**Comment by honkmaster** [comment] 2016-01-20 18:07
![unknown](https://cloud.githubusercontent.com/assets/1380397/12458201/fb7914ea-bfa8-11e5-9388-3530ff221850.jpeg)

**Closed** 2016-01-20 22:18 UTC

**Comment by Marley-crewcut** [comment] 2025-10-12 18:19
> Thanks. you can ping me if you need any help.
> 
> Cheers





https://plumewayne811.github.io/GJq3gcHIopS6gqptfBPPYxcDbcbpJDhQKJqvTHKEX5j-JzJcMdid0xJ4QssiQLOarn36WqU/
