### ISSUE TITLE
Background layer animates frame on first show for custom and black types

### ISSUE THREAD

**Issue by ricsantos** [SVProgressHUD/SVProgressHUD#795] opened 2017-08-28 03:22 UTC
When using mask type `custom` or `black`, the first time the HUD is shown it can be seen to animate the background layer's frame size from zero to full screen.

I tested a few older versions of SVProgressHUD and it appears the bug was introduced in v2.1 (v2.0.4 does not show this behaviour).

Attached is a demo project showing the issue.
[HUDTest.zip](https://github.com/SVProgressHUD/SVProgressHUD/files/1254999/HUDTest.zip)

And here is a screen capture (iOS simulator slow animations enabled):
![hudtest](https://user-images.githubusercontent.com/989890/29758052-95e8e5c8-8bef-11e7-9623-b2ea252db43c.gif)

**Comment by honkmaster** [comment] 2017-09-06 22:38
Due to changes in iOS 11 and problems with UIVisualEffectView I remodelled the show / hide animation. I will check tomorrow If your issue is fixed with my changed, else work on it.

**Comment by honkmaster** [comment] 2017-09-07 17:37
I can not reproduce the issue in our demo project, however, I can reproduce it in your demo.

**Comment by honkmaster** [comment] 2017-09-07 17:59
So, I updated the Podfile to 2.2 (the new release). Everything is working as expected.
![fadein](https://user-images.githubusercontent.com/1380397/30177719-fd31a138-9406-11e7-9078-f212195ef404.gif)

**Closed by honkmaster** 2017-09-07 17:59 UTC
Labels: Under investigation
